### ISSUE TITLE
Version 1

### ISSUE THREAD

**Issue by dmca-glasgow** [UofGAnalytics/build-coursework#1]
## Compile courses
When the build script is executed from a directory containing a `course.yaml` file, it will create an `html` directory containing an HTML file for each unit listed under `units` in the `course.yaml` file.

#### Course.yaml file
- [x] Loop through YAML files referenced under `units`

`type`? 
`public`?
`moodleid`?
`catalog`?
`authors`?
`academic_year`?
`start_date`?

#### Unit YAML file
- [x] Loop through .*md files referenced under `content` and run Markdown to HTML script

`name`?
`title`?
`golive`?

- [x] Concatenate resulting HTML and wrap with accessible website HTML template
- [ ] Accomodate other [output options](https://github.com/UofGAnalytics/build-coursework/issues/2)
- [ ] Watch mode to give live preview in browser as Markdown is authored

## Markdown to HTML script
- [x] Code syntax highlighting
- [x] Parse non-standard code-block language config, ie. `{r,echo=TRUE}`
- [x] Optionally execute R code
  - [x] Display text output
  - [x] Display graph output
  - [x] Cache results
- [x] Inline (base64 encode) referenced images
  - [x] Ensure author has added `alt` text to image for accessibility
- [ ] All custom Markdown functionality in the [kitchen sink course](https://github.com/UofGAnalytics/build-coursework/issues/3)

## Accessible website template
- [x] Minimal wrapper around Coursework
- [x] Responsive
- [ ] Styling for all [Markdown compatible syntax](https://daringfireball.net/projects/markdown/syntax)
- [x] Styling for custom Markdown functionality 
  - [x] YouTube videos
  - [x] Render LaTex
  - [x] Images (including R graphs)
  - [x] More custom Markdown #7 
- [x] Accessibility toolbar
  - [x] Change font-size
  - [x] Change background colour
  - [x] Change text colour
- [ ] Keyboard-based navigation
- [ ] Speech-based navigation

#### Auth
- [ ] LDAP auth (allow login via GUID)
- [ ] LTI auth (allow login via Moodle External Tool links)

#### Making coursework available
- [ ] Allow staff to drag and drop zip file via browser
