### ISSUE TITLE
Probability and Sampling Fundamentals TODO

### ISSUE THREAD

**Issue by dmca-glasgow** [UofGAnalytics/build-coursework#33]
- [x] Accessibility view options are buggy
 - [x] ref://tennis in Week 4
 - [x] Remove "\mbox{}" occurrences
 - [x] Boxout counter doesn't increment when split between markdown files (rprog week 1)
 - [x] Disable warnings from pdfjs - beginGroup and endGroup
 - [x] Display of videos nested inside answers
 - [x] Scaling of pdf graphics
 - [x] Footnotes not working as expected
 - [x] ####[task, optional]
 - [x] ####[proposition]
 - [x] Windows - figures built using ggplot2
 - [x] Puppetteer (render PDFs) not working on Windows
