### ISSUE TITLE
Notes on R Programming coursework

### ISSUE THREAD

**Issue by dmca-glasgow** [UofGAnalytics/build-coursework#7]
### LaTeX
- [x] Inline tex (everywhere)
```
$\frac56$
```
- [x] Latex with no delimiters [here](https://github.com/UofGAnalytics/BOLDrprog/blob/5bbc3ed5d24d85791ff1dde069c9a4fd76197cf3/coursematerial/week3/review.Rmd#L77-L82)?

### Macros

- [x] Youtube video link
```
###[video, videoid="mjDbSsKkVdc", duration="3m52s"]A brief history of computing
```
- [x] Wrappers with different icons
```
###[weblink, target="http://r4ds.had.co.nz/", icon="book"]
###[/weblink]

####[example]
####[/example]

####[supplement] Differences between the assignment operators
####[/supplement]

####[background]The exposition pipe operator from magrittr
####[/background]
```
- [x] Task/Answer
Answers are written inline but in the output they are listed at the end
```
####[task, label="task_alcohol_classic"]Binary numbers
Question?
#####[answer]
Answer
#####[/answer]
####[/task]
```
- [ ] Columns ([Sample](https://github.com/UofGAnalytics/BOLDrprog/blob/e8e46dfb780487b8156bd51d0b56891f0e484b9e/coursematerial/week6/review.Rmd#L14-L41))
```
####[columns]
#####[column, width=12]
#####[/column]
####[/columns]
```

### Code blocks
Mimic functionality outlined [here](https://github.com/UofGAnalytics/BOLDrprog/blob/68f2810bc83b27f8c902221782134236339b226f/coursematerial/week10/rmarkdown.Rmd#L74).
- [x] "Code chunks" concept
- [x] Extra properties as below
```
codeblock{r, echo=FALSE, fig.width=10, fig.height=6, out.width=".75\\textwidth"}
```

### Images
- [x] Should all figures/images be moved to the top of a page?
- [x] Has custom template displaying "Figure 1: Screenshot from SAS Enterprise Miner" below
```
![Screenshot from SAS Enterprise Miner](eminer.png)
```
- [x] Importing of pdfs as images
```
![](tidyr_figure.pdf)
```

### Test these through SVG grapher

- [ ] [persp](https://github.com/UofGAnalytics/BOLDrprog/blob/5bbc3ed5d24d85791ff1dde069c9a4fd76197cf3/coursematerial/week5/threed.Rmd#L51)
- [ ] [facet_wrap](https://github.com/UofGAnalytics/BOLDrprog/blob/5bbc3ed5d24d85791ff1dde069c9a4fd76197cf3/coursematerial/week6/examples.Rmd#L72)
- [ ] [qplot](https://github.com/UofGAnalytics/BOLDrprog/blob/5bbc3ed5d24d85791ff1dde069c9a4fd76197cf3/coursematerial/week6/qplot.Rmd#L33)
- [ ] Contour plots Claire sent on Teams

### Misc.

- [ ] Do we control this server? http://www.stats.gla.ac.uk/~levers/rp/addresses.RData
- [ ] `\mbox{ }` ? ([Sample 1](https://github.com/UofGAnalytics/BOLDrprog/blob/e8e46dfb780487b8156bd51d0b56891f0e484b9e/coursematerial/week2/review.Rmd#L9-L11), [Sample 2](https://github.com/UofGAnalytics/BOLDrprog/blob/e8e46dfb780487b8156bd51d0b56891f0e484b9e/coursematerial/week2/review.Rmd#L42))
